### ISSUE TITLE
Installation as a npm package fails

### ISSUE THREAD

**Issue by exsilium** [pylonide/pylon#56]
Installation of Pylon as a npm package fails due to the postinstall step and the different location of ace editor:

```
> pln@2.3.0 postinstall /Users/xxx/Projects/pylon_npm/node_modules/pln
> cd node_modules/ace; make clean pre_build; ./Makefile.dryice.js minimal; cd ../..; make worker

sh: line 0: cd: node_modules/ace: No such file or directory
```

**Comment by exsilium** [comment]
```
> pln@2.3.0 postinstall /home/xxx/pylon_npm/node_modules/pln
> make worker

mkdir -p plugins-client/lib.ace/www/worker
rm -rf /tmp/pln_worker_build
mkdir -p /tmp/pln_worker_build/ext
ln -s `pwd`/plugins-client/ext.language /tmp/pln_worker_build/ext/language
ln -s `pwd`/plugins-client/ext.codecomplete /tmp/pln_worker_build/ext/codecomplete
ln -s `pwd`/plugins-client/ext.jslanguage /tmp/pln_worker_build/ext/jslanguage
ln -s `pwd`/plugins-client/ext.csslanguage /tmp/pln_worker_build/ext/csslanguage
ln -s `pwd`/plugins-client/ext.htmllanguage /tmp/pln_worker_build/ext/htmllanguage
ln -s `pwd`/plugins-client/ext.linereport /tmp/pln_worker_build/ext/linereport
ln -s `pwd`/plugins-client/ext.linereport_php /tmp/pln_worker_build/ext/linereport_php
ln -s `pwd`/plugins-client/ext.linereport_python /tmp/pln_worker_build/ext/linereport_python
node Makefile.dryice.js worker
# cloud9 worker ---------
/home/xxx/pylon_npm/node_modules/dryice/lib/dryice/index.js:654
      throw new Error('Each commonjs root should be a directory: ' + root);
      ^

Error: Each commonjs root should be a directory: /home/xxx/pylon_npm/node_modules/pln/node_modules/ace/lib
    at CommonJsProject.<anonymous> (/home/xxx/pylon_npm/node_modules/dryice/lib/dryice/index.js:654:13)
    at Array.map (<anonymous>)
    at new CommonJsProject (/home/xxx/pylon_npm/node_modules/dryice/lib/dryice/index.js:652:27)
    at Function.copy.createCommonJsProject (/home/xxx/pylon_npm/node_modules/dryice/lib/dryice/index.js:981:10)
    at worker (/home/xxx/pylon_npm/node_modules/pln/Makefile.dryice.js:43:30)
    at main (/home/xxx/pylon_npm/node_modules/pln/Makefile.dryice.js:35:9)
    at Object.<anonymous> (/home/xxx/pylon_npm/node_modules/pln/Makefile.dryice.js:99:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
Makefile:70: recipe for target 'plugins-client/lib.ace/www/worker/worker-language.js' failed
make: *** [plugins-client/lib.ace/www/worker/worker-language.js] Error 1
```
