### ISSUE TITLE
node v10.13.0 not working: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by Morabaraba** [pylonide/pylon#59]
```sh
air:pylon d-_-b$ bin/pylon.sh -w $HOME/prj
make: Nothing to be done for `worker'.
OSX
connect plugin start
Connect server listening at http://localhost:3131
While starting the '/Users/d-_-b/prj/pylon/configs/default':
/Users/d-_-b/prj/pylon/server.js:117
	       throw err;
	       ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.mkdir (fs.js:719:14)
    at Object.startup [as setup] (/Users/d-_-b/prj/pylon/plugins-server/connect.session.file/session-ext.js:15:12)
    at startPlugins (/Users/d-_-b/prj/pylon/node_modules/architect/architect.js:474:24)
    at startPlugins (/Users/d-_-b/prj/pylon/node_modules/architect/architect.js:482:21)
    at register (/Users/d-_-b/prj/pylon/node_modules/architect/architect.js:513:13)
    at Server.<anonymous> (/Users/d-_-b/prj/pylon/plugins-server/connect/connect-plugin.js:86:13)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1320:10)
air:pylon d-_-b$ node -v
v10.13.0
```

Gives the same error for `v11.1.0` works great with `v4.9.1`.

Congrats on the name change!

**Comment by exsilium** [comment]
Confirmed... and thanks!
